name = "nfd-bot"
main = "worker.js"
compatibility_date = "2025-11-12"

# 环境变量（通过 GitHub Secrets 注入）
[vars]
ENV_BOT_TOKEN = ""
ENV_BOT_SECRET = ""
ENV_ADMIN_UID = ""

# KV 命名空间（必须先在 Cloudflare 创建）
[[kv_namespaces]]
binding = "NFD_KV"
id = "6abe78e21a124170ac75236b27b4d76f"
