name = "nfd"
main = "worker.js"
compatibility_date = "2025-11-12"

[vars]
ENV_BOT_TOKEN = "${BOT_TOKEN}"
ENV_BOT_SECRET = "${BOT_SECRET}"
ENV_ADMIN_UID = "${ADMIN_UID}"

[[kv_namespaces]]
binding = "nfd"
id = "6abe78e21a124170ac75236b27b4d76"
